// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {services} from '../models';
import {hottrend} from '../models';
import {tools} from '../models';
import {mcp} from '../models';

export function AddAgentConfig(arg1:models.AgentConfig):Promise<string>;

export function AddMCPServer(arg1:models.MCPServerConfig):Promise<string>;

export function AddPaperPosition(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function AddStockGroupDef(arg1:string):Promise<models.StockGroup>;

export function AddStrategy(arg1:models.Strategy):Promise<string>;

export function AddToWatchlist(arg1:models.Stock):Promise<string>;

export function ApplyPaperExitRules():Promise<number>;

export function AskBoardReport(arg1:main.AskBoardReportRequest):Promise<main.AskBoardReportResponse>;

export function BackfillAllHistory(arg1:number,arg2:boolean):Promise<models.HistoryBackfillResult>;

export function BackfillHistory(arg1:models.HistoryBackfillRequest):Promise<models.HistoryBackfillResult>;

export function BackfillWatchlistHistory(arg1:number):Promise<models.HistoryBackfillResult>;

export function CancelInterruptedMeeting(arg1:string):Promise<boolean>;

export function CancelMeeting(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<services.UpdateInfo>;

export function ClearSessionMessages(arg1:string):Promise<string>;

export function ClosePaperPosition(arg1:number,arg2:number):Promise<string>;

export function CollectDailyHistory(arg1:models.HistoryCollectRequest):Promise<models.HistoryCollectResult>;

export function DeleteAgentConfig(arg1:string):Promise<string>;

export function DeleteMCPServer(arg1:string):Promise<string>;

export function DeletePaperPosition(arg1:number):Promise<string>;

export function DeleteStockGroupDef(arg1:string):Promise<string>;

export function DeleteStrategy(arg1:string):Promise<string>;

export function DeleteTradeJournal(arg1:number):Promise<string>;

export function DoUpdate():Promise<string>;

export function EnhancePrompt(arg1:main.EnhancePromptRequest):Promise<main.EnhancePromptResponse>;

export function EnrichBacktestData(arg1:number,arg2:boolean):Promise<models.HistoryBackfillResult>;

export function GenerateBoardReport(arg1:main.GenerateBoardReportRequest):Promise<main.GenerateBoardReportResponse>;

export function GenerateStrategy(arg1:main.GenerateStrategyRequest):Promise<main.GenerateStrategyResponse>;

export function GetCachedBoardReport(arg1:string,arg2:string):Promise<main.GetCachedBoardReportResponse>;

export function GetActiveStrategyID():Promise<string>;

export function GetAgentConfigs():Promise<Array<models.AgentConfig>>;

export function GetAllHotTrends():Promise<Array<hottrend.HotTrendResult>>;

export function GetAvailableTools():Promise<Array<tools.ToolInfo>>;

export function GetBoardFundFlow(arg1:string,arg2:number,arg3:number):Promise<models.BoardFundFlowList>;

export function GetBoardFundFlowOverview(arg1:string,arg2:number):Promise<models.BoardFundFlowOverview>;

export function GetBoardFundFlowTracking(arg1:string,arg2:number,arg3:string):Promise<models.BoardFundFlowTracking>;

export function GetBoardLeaders(arg1:string,arg2:number):Promise<models.BoardLeaderList>;

export function GetConfig():Promise<models.AppConfig>;

export function GetCurrentVersion():Promise<string>;

export function GetF10Overview(arg1:string):Promise<models.F10Overview>;

export function GetF10Valuation(arg1:string):Promise<models.StockValuation>;

export function GetHeldPositions():Promise<Array<models.HeldPosition>>;

export function GetHistoryAutoCollectStatus():Promise<models.HistoryAutoCollectStatus>;

export function GetHotTrend(arg1:string):Promise<hottrend.HotTrendResult>;

export function GetHotTrendPlatforms():Promise<Array<hottrend.PlatformInfo>>;

export function GetKLineData(arg1:string,arg2:string,arg3:number):Promise<Array<models.KLineData>>;

export function GetLongHuBangDetail(arg1:string,arg2:string):Promise<Array<models.LongHuBangDetail>>;

export function GetLongHuBangList(arg1:number,arg2:number,arg3:string):Promise<services.LongHuBangListResult>;

export function GetMCPServerTools(arg1:string):Promise<Array<mcp.ToolInfo>>;

export function GetMCPServers():Promise<Array<models.MCPServerConfig>>;

export function GetMCPStatus():Promise<Array<mcp.ServerStatus>>;

export function GetMarketChangeDistribution(arg1:boolean):Promise<models.MarketChangeDistribution>;

export function GetMarketIndices():Promise<Array<models.MarketIndex>>;

export function GetMarketRegime():Promise<models.MarketRegime>;

export function GetMarketStatus():Promise<services.MarketStatus>;

export function GetMarketStylePreference():Promise<models.MarketStylePreference>;

export function GetOpenClawStatus():Promise<Record<string, any>>;

export function GetOrCreateSession(arg1:string,arg2:string):Promise<models.StockSession>;

export function GetOrderBook(arg1:string):Promise<models.OrderBook>;

export function GetPaperRiskSummary():Promise<models.PaperRiskSummary>;

export function GetPaperStats():Promise<models.PaperStats>;

export function GetSessionMessages(arg1:string):Promise<Array<models.ChatMessage>>;

export function GetStockGroupDefs():Promise<Array<models.StockGroup>>;

export function GetStockGroups():Promise<Record<string, Array<string>>>;

export function GetStockMoves(arg1:string,arg2:number,arg3:number):Promise<models.StockMoveList>;

export function GetStockRealTimeData(arg1:Array<string>):Promise<Array<models.Stock>>;

export function GetStrategies():Promise<Array<models.Strategy>>;

export function GetStrategyNextDayReview(arg1:models.StrategyReviewRequest):Promise<models.StrategyReviewResult>;

export function GetTailForwardConfig():Promise<models.TailForwardConfig>;

export function GetTelegraphList():Promise<Array<services.Telegraph>>;

export function GetTradeDates(arg1:number):Promise<Array<string>>;

export function GetTradeJournal():Promise<Array<models.TradeJournalEntry>>;

export function GetTradeJournalStats():Promise<models.TradeJournalStats>;

export function GetTradingSchedule():Promise<services.TradingSchedule>;

export function GetWatchlist():Promise<Array<models.Stock>>;

export function Greet(arg1:string):Promise<string>;

export function ListPaperPositions():Promise<Array<models.PaperPosition>>;

export function NotifyFrontendReady():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PushSignal(arg1:models.PushSignal):Promise<models.PushResult>;

export function RefreshFundamentals():Promise<string>;

export function RefreshFundamentalsHistory():Promise<string>;

export function RemoveFromWatchlist(arg1:string):Promise<string>;

export function RenameStockGroupDef(arg1:string,arg2:string):Promise<string>;

export function ReopenPaperPosition(arg1:number):Promise<string>;

export function RestartApp():Promise<string>;

export function RetryAgent(arg1:string,arg2:string,arg3:string):Promise<models.ChatMessage>;

export function RetryAgentAndContinue(arg1:string):Promise<Array<models.ChatMessage>>;

export function RunAfterMarketCheckOnce():Promise<number>;

export function RunBacktest(arg1:models.BacktestRequest):Promise<models.BacktestResult>;

export function RunCaoYuanStandardScanner4A(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunCaoYuanZhuangScanner4B(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunDipEntryScannerV8(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunFundamentalScan(arg1:string):Promise<models.FundamentalScanResult>;

export function RunHotMoneyBreakoutScannerV7(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunLateDayChaseScanner(arg1:models.LateDayChaseScannerRequest):Promise<models.LateDayChaseScannerResult>;

export function RunLimitPullbackScanner(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunLowBuyBatchReplay(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.LowBuyBatchResult>;

export function RunLowBuyReplayOnDate(arg1:string,arg2:number,arg3:number):Promise<models.LowBuyScannerResult>;

export function RunLowBuyScannerV1(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunMonsterScannerV10(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunMonsterScannerV9(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunPaperStrategyAccount(arg1:string):Promise<models.StrategyAccountResult>;

export function RunPortfolioBacktest(arg1:models.BacktestRequest):Promise<models.BacktestResult>;

export function RunPositionMonitorOnce():Promise<number>;

export function RunStrategyAccount(arg1:string,arg2:number):Promise<models.StrategyAccountResult>;

export function RunStrategyAccountRisk(arg1:string,arg2:number):Promise<models.StrategyAccountResult>;

export function RunTailBuyScannerV6(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunTailForwardScan(arg1:string,arg2:boolean):Promise<models.TailForwardResult>;

export function RunTailForwardScanAll(arg1:boolean):Promise<models.TailForwardResult>;

export function RunTailLazyBatchReplay(arg1:string,arg2:string):Promise<models.TailLazyBatchResult>;

export function RunTailLazyReplayOnDate(arg1:string,arg2:number):Promise<models.LowBuyScannerResult>;

export function RunTailLazyScannerV2(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunTripleVolumeScannerV5(arg1:models.LowBuyScannerRequest):Promise<models.LowBuyScannerResult>;

export function RunWaveBacktest(arg1:models.BacktestRequest):Promise<models.BacktestResult>;

export function RunWaveScanner():Promise<models.WaveScanResult>;

export function RunWaveScannerWithGate(arg1:boolean):Promise<models.WaveScanResult>;

export function SaveTradeJournal(arg1:models.TradeJournalRequest):Promise<string>;

export function SearchStocks(arg1:string):Promise<Array<services.StockSearchResult>>;

export function SellStockPosition(arg1:string,arg2:number,arg3:string):Promise<string>;

export function SendMeetingMessage(arg1:main.MeetingMessageRequest):Promise<Array<models.ChatMessage>>;

export function SetActiveStrategy(arg1:string):Promise<string>;

export function SetStockGroups(arg1:string,arg2:Array<string>):Promise<string>;

export function SetTailForwardConfig(arg1:boolean,arg2:boolean):Promise<string>;

export function SyncTradeJournalWatchGroup():Promise<string>;

export function TestAIConnection(arg1:models.AIConfig):Promise<string>;

export function TestMCPConnection(arg1:string):Promise<mcp.ServerStatus>;

export function TestPush():Promise<models.PushResult>;

export function UpdateAgentConfig(arg1:models.AgentConfig):Promise<string>;

export function UpdateConfig(arg1:models.AppConfig):Promise<string>;

export function UpdateHistoryAutoCollect(arg1:models.HistoryAutoCollectRequest):Promise<models.HistoryAutoCollectStatus>;

export function UpdateMCPServer(arg1:models.MCPServerConfig):Promise<string>;

export function UpdatePaperPosition(arg1:number,arg2:number,arg3:number):Promise<string>;

export function UpdateStockPosition(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function UpdateStrategy(arg1:models.Strategy):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
