// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentConfig(arg1) {
  return window['go']['main']['App']['AddAgentConfig'](arg1);
}

export function AddIntelNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddIntelNote'](arg1, arg2, arg3);
}

export function AddIntelNoteFromUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddIntelNoteFromUpload'](arg1, arg2, arg3);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddPaperPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddPaperPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function AddStockGroupDef(arg1) {
  return window['go']['main']['App']['AddStockGroupDef'](arg1);
}

export function AddStrategy(arg1) {
  return window['go']['main']['App']['AddStrategy'](arg1);
}

export function AddTipPicks(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTipPicks'](arg1, arg2, arg3);
}

export function AddToWatchlist(arg1) {
  return window['go']['main']['App']['AddToWatchlist'](arg1);
}

export function AddXSignalsManual(arg1) {
  return window['go']['main']['App']['AddXSignalsManual'](arg1);
}

export function ApplyPaperExitRules() {
  return window['go']['main']['App']['ApplyPaperExitRules']();
}

export function AskBoardReport(arg1) {
  return window['go']['main']['App']['AskBoardReport'](arg1);
}

export function BackfillAllHistory(arg1, arg2) {
  return window['go']['main']['App']['BackfillAllHistory'](arg1, arg2);
}

export function BackfillHistory(arg1) {
  return window['go']['main']['App']['BackfillHistory'](arg1);
}

export function BackfillMissingOHLC(arg1) {
  return window['go']['main']['App']['BackfillMissingOHLC'](arg1);
}

export function BackfillOversoldLearn(arg1) {
  return window['go']['main']['App']['BackfillOversoldLearn'](arg1);
}

export function BackfillWatchlistHistory(arg1) {
  return window['go']['main']['App']['BackfillWatchlistHistory'](arg1);
}

export function BacktestLimitupRetrace(arg1, arg2) {
  return window['go']['main']['App']['BacktestLimitupRetrace'](arg1, arg2);
}

export function BacktestSecondWave(arg1, arg2) {
  return window['go']['main']['App']['BacktestSecondWave'](arg1, arg2);
}

export function CancelInterruptedMeeting(arg1) {
  return window['go']['main']['App']['CancelInterruptedMeeting'](arg1);
}

export function CancelMeeting(arg1) {
  return window['go']['main']['App']['CancelMeeting'](arg1);
}

export function CheckDataFreshness() {
  return window['go']['main']['App']['CheckDataFreshness']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearAllPaperPositions() {
  return window['go']['main']['App']['ClearAllPaperPositions']();
}

export function ClearPaperPositionsByIDs(arg1) {
  return window['go']['main']['App']['ClearPaperPositionsByIDs'](arg1);
}

export function ClearSessionMessages(arg1) {
  return window['go']['main']['App']['ClearSessionMessages'](arg1);
}

export function ClosePaperPosition(arg1, arg2) {
  return window['go']['main']['App']['ClosePaperPosition'](arg1, arg2);
}

export function CollectDailyHistory(arg1) {
  return window['go']['main']['App']['CollectDailyHistory'](arg1);
}

export function CountAppInstances() {
  return window['go']['main']['App']['CountAppInstances']();
}

export function DebugOversoldIgnite(arg1, arg2) {
  return window['go']['main']['App']['DebugOversoldIgnite'](arg1, arg2);
}

export function DecideEvolutionProposal(arg1, arg2) {
  return window['go']['main']['App']['DecideEvolutionProposal'](arg1, arg2);
}

export function DeleteAgentConfig(arg1) {
  return window['go']['main']['App']['DeleteAgentConfig'](arg1);
}

export function DeleteIntelNote(arg1) {
  return window['go']['main']['App']['DeleteIntelNote'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeletePaperPosition(arg1) {
  return window['go']['main']['App']['DeletePaperPosition'](arg1);
}

export function DeleteRemoteUser(arg1) {
  return window['go']['main']['App']['DeleteRemoteUser'](arg1);
}

export function DeleteStockGroupDef(arg1) {
  return window['go']['main']['App']['DeleteStockGroupDef'](arg1);
}

export function DeleteStrategy(arg1) {
  return window['go']['main']['App']['DeleteStrategy'](arg1);
}

export function DeleteTradeJournal(arg1) {
  return window['go']['main']['App']['DeleteTradeJournal'](arg1);
}

export function DiagnoseLimitupRetrace() {
  return window['go']['main']['App']['DiagnoseLimitupRetrace']();
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function EnhancePrompt(arg1) {
  return window['go']['main']['App']['EnhancePrompt'](arg1);
}

export function EnrichBacktestData(arg1, arg2) {
  return window['go']['main']['App']['EnrichBacktestData'](arg1, arg2);
}

export function ForUser(arg1) {
  return window['go']['main']['App']['ForUser'](arg1);
}

export function GenerateBoardReport(arg1) {
  return window['go']['main']['App']['GenerateBoardReport'](arg1);
}

export function GenerateEvolutionProposalsNow() {
  return window['go']['main']['App']['GenerateEvolutionProposalsNow']();
}

export function GenerateIntelDigest(arg1) {
  return window['go']['main']['App']['GenerateIntelDigest'](arg1);
}

export function GenerateStrategy(arg1) {
  return window['go']['main']['App']['GenerateStrategy'](arg1);
}

export function GetAIReportCalibration() {
  return window['go']['main']['App']['GetAIReportCalibration']();
}

export function GetActiveStrategyID() {
  return window['go']['main']['App']['GetActiveStrategyID']();
}

export function GetAgentConfigs() {
  return window['go']['main']['App']['GetAgentConfigs']();
}

export function GetAllHotTrends() {
  return window['go']['main']['App']['GetAllHotTrends']();
}

export function GetArchiveBars(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetArchiveBars'](arg1, arg2, arg3, arg4);
}

export function GetArchiveCoverage() {
  return window['go']['main']['App']['GetArchiveCoverage']();
}

export function GetArchiveKLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetArchiveKLine'](arg1, arg2, arg3, arg4);
}

export function GetArchiveStockInfo(arg1) {
  return window['go']['main']['App']['GetArchiveStockInfo'](arg1);
}

export function GetAuctionFinal(arg1, arg2) {
  return window['go']['main']['App']['GetAuctionFinal'](arg1, arg2);
}

export function GetAuctionPicksC(arg1) {
  return window['go']['main']['App']['GetAuctionPicksC'](arg1);
}

export function GetAuctionPicksG(arg1) {
  return window['go']['main']['App']['GetAuctionPicksG'](arg1);
}

export function GetAuditLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAuditLogs'](arg1, arg2, arg3, arg4);
}

export function GetAuditUsers() {
  return window['go']['main']['App']['GetAuditUsers']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetBackendMode() {
  return window['go']['main']['App']['GetBackendMode']();
}

export function GetBackupStatus() {
  return window['go']['main']['App']['GetBackupStatus']();
}

export function GetBoardFundFlow(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBoardFundFlow'](arg1, arg2, arg3);
}

export function GetBoardFundFlowOverview(arg1, arg2) {
  return window['go']['main']['App']['GetBoardFundFlowOverview'](arg1, arg2);
}

export function GetBoardFundFlowTracking(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBoardFundFlowTracking'](arg1, arg2, arg3);
}

export function GetBoardLeaders(arg1, arg2) {
  return window['go']['main']['App']['GetBoardLeaders'](arg1, arg2);
}

export function GetBoardReportStatus(arg1, arg2) {
  return window['go']['main']['App']['GetBoardReportStatus'](arg1, arg2);
}

export function GetBoardResealWatch() {
  return window['go']['main']['App']['GetBoardResealWatch']();
}

export function GetCachedBoardReport(arg1, arg2) {
  return window['go']['main']['App']['GetCachedBoardReport'](arg1, arg2);
}

export function GetCninfoAnnouncements(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCninfoAnnouncements'](arg1, arg2, arg3);
}

export function GetCompositeValidation() {
  return window['go']['main']['App']['GetCompositeValidation']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigMasked() {
  return window['go']['main']['App']['GetConfigMasked']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDrillSession(arg1, arg2) {
  return window['go']['main']['App']['GetDrillSession'](arg1, arg2);
}

export function GetEvolutionProposals(arg1) {
  return window['go']['main']['App']['GetEvolutionProposals'](arg1);
}

export function GetF10Overview(arg1) {
  return window['go']['main']['App']['GetF10Overview'](arg1);
}

export function GetF10Valuation(arg1) {
  return window['go']['main']['App']['GetF10Valuation'](arg1);
}

export function GetGubaSentiment(arg1, arg2) {
  return window['go']['main']['App']['GetGubaSentiment'](arg1, arg2);
}

export function GetHeldPositions() {
  return window['go']['main']['App']['GetHeldPositions']();
}

export function GetHistoryAutoCollectStatus() {
  return window['go']['main']['App']['GetHistoryAutoCollectStatus']();
}

export function GetHistoryMinuteBackfillStatus() {
  return window['go']['main']['App']['GetHistoryMinuteBackfillStatus']();
}

export function GetHistoryMinuteCoverage() {
  return window['go']['main']['App']['GetHistoryMinuteCoverage']();
}

export function GetHotTrend(arg1) {
  return window['go']['main']['App']['GetHotTrend'](arg1);
}

export function GetHotTrendPlatforms() {
  return window['go']['main']['App']['GetHotTrendPlatforms']();
}

export function GetIntradayCoverage() {
  return window['go']['main']['App']['GetIntradayCoverage']();
}

export function GetKLineData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKLineData'](arg1, arg2, arg3);
}

export function GetLearnOverview() {
  return window['go']['main']['App']['GetLearnOverview']();
}

export function GetLongHuBangDetail(arg1, arg2) {
  return window['go']['main']['App']['GetLongHuBangDetail'](arg1, arg2);
}

export function GetLongHuBangList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLongHuBangList'](arg1, arg2, arg3);
}

export function GetMCPServerTools(arg1) {
  return window['go']['main']['App']['GetMCPServerTools'](arg1);
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMarketChangeDistribution(arg1) {
  return window['go']['main']['App']['GetMarketChangeDistribution'](arg1);
}

export function GetMarketIndices() {
  return window['go']['main']['App']['GetMarketIndices']();
}

export function GetMarketMood() {
  return window['go']['main']['App']['GetMarketMood']();
}

export function GetMarketRegime() {
  return window['go']['main']['App']['GetMarketRegime']();
}

export function GetMarketStatus() {
  return window['go']['main']['App']['GetMarketStatus']();
}

export function GetMarketStylePreference() {
  return window['go']['main']['App']['GetMarketStylePreference']();
}

export function GetMinuteHistory(arg1, arg2) {
  return window['go']['main']['App']['GetMinuteHistory'](arg1, arg2);
}

export function GetOpenClawStatus() {
  return window['go']['main']['App']['GetOpenClawStatus']();
}

export function GetOrCreateSession(arg1, arg2) {
  return window['go']['main']['App']['GetOrCreateSession'](arg1, arg2);
}

export function GetOrderBook(arg1) {
  return window['go']['main']['App']['GetOrderBook'](arg1);
}

export function GetOversoldLearnReport() {
  return window['go']['main']['App']['GetOversoldLearnReport']();
}

export function GetPaperAutoPaused() {
  return window['go']['main']['App']['GetPaperAutoPaused']();
}

export function GetPaperRiskSummary() {
  return window['go']['main']['App']['GetPaperRiskSummary']();
}

export function GetPaperStats() {
  return window['go']['main']['App']['GetPaperStats']();
}

export function GetResearchReport(arg1) {
  return window['go']['main']['App']['GetResearchReport'](arg1);
}

export function GetResearchReportHTML(arg1) {
  return window['go']['main']['App']['GetResearchReportHTML'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetStockFocusTicks(arg1, arg2) {
  return window['go']['main']['App']['GetStockFocusTicks'](arg1, arg2);
}

export function GetStockGroupDefs() {
  return window['go']['main']['App']['GetStockGroupDefs']();
}

export function GetStockGroups() {
  return window['go']['main']['App']['GetStockGroups']();
}

export function GetStockIntraday(arg1, arg2) {
  return window['go']['main']['App']['GetStockIntraday'](arg1, arg2);
}

export function GetStockMoves(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockMoves'](arg1, arg2, arg3);
}

export function GetStockRealTimeData(arg1) {
  return window['go']['main']['App']['GetStockRealTimeData'](arg1);
}

export function GetStrategies() {
  return window['go']['main']['App']['GetStrategies']();
}

export function GetStrategyLearnReport(arg1) {
  return window['go']['main']['App']['GetStrategyLearnReport'](arg1);
}

export function GetStrategyNextDayReview(arg1) {
  return window['go']['main']['App']['GetStrategyNextDayReview'](arg1);
}

export function GetTailForwardConfig() {
  return window['go']['main']['App']['GetTailForwardConfig']();
}

export function GetTelegraphList() {
  return window['go']['main']['App']['GetTelegraphList']();
}

export function GetTradeDates(arg1) {
  return window['go']['main']['App']['GetTradeDates'](arg1);
}

export function GetTradeJournal() {
  return window['go']['main']['App']['GetTradeJournal']();
}

export function GetTradeJournalStats() {
  return window['go']['main']['App']['GetTradeJournalStats']();
}

export function GetTradingSchedule() {
  return window['go']['main']['App']['GetTradingSchedule']();
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function GetWaveScanStatus() {
  return window['go']['main']['App']['GetWaveScanStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportAIReport(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ImportAIReport'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function IngestXPosts(arg1) {
  return window['go']['main']['App']['IngestXPosts'](arg1);
}

export function IsTrustedRemoteUser(arg1) {
  return window['go']['main']['App']['IsTrustedRemoteUser'](arg1);
}

export function LearnAllStrategiesNow() {
  return window['go']['main']['App']['LearnAllStrategiesNow']();
}

export function LearnOversoldNow() {
  return window['go']['main']['App']['LearnOversoldNow']();
}

export function ListIntelNotes(arg1, arg2) {
  return window['go']['main']['App']['ListIntelNotes'](arg1, arg2);
}

export function ListPaperPositions() {
  return window['go']['main']['App']['ListPaperPositions']();
}

export function ListRemoteUsers() {
  return window['go']['main']['App']['ListRemoteUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function NotifyFrontendReady() {
  return window['go']['main']['App']['NotifyFrontendReady']();
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PushSignal(arg1) {
  return window['go']['main']['App']['PushSignal'](arg1);
}

export function RealizedPnLOfStock(arg1) {
  return window['go']['main']['App']['RealizedPnLOfStock'](arg1);
}

export function ReduceStockPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReduceStockPosition'](arg1, arg2, arg3, arg4);
}

export function RefreshFundamentals() {
  return window['go']['main']['App']['RefreshFundamentals']();
}

export function RefreshFundamentalsHistory() {
  return window['go']['main']['App']['RefreshFundamentalsHistory']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['main']['App']['RemoveFromWatchlist'](arg1);
}

export function RenameStockGroupDef(arg1, arg2) {
  return window['go']['main']['App']['RenameStockGroupDef'](arg1, arg2);
}

export function ReopenPaperPosition(arg1) {
  return window['go']['main']['App']['ReopenPaperPosition'](arg1);
}

export function RepairQfqGaps(arg1) {
  return window['go']['main']['App']['RepairQfqGaps'](arg1);
}

export function ReportFrontendError(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReportFrontendError'](arg1, arg2, arg3);
}

export function ReprobeBackend() {
  return window['go']['main']['App']['ReprobeBackend']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RetryAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryAgent'](arg1, arg2, arg3);
}

export function RetryAgentAndContinue(arg1) {
  return window['go']['main']['App']['RetryAgentAndContinue'](arg1);
}

export function RunAfterMarketCheckOnce() {
  return window['go']['main']['App']['RunAfterMarketCheckOnce']();
}

export function RunBacktest(arg1) {
  return window['go']['main']['App']['RunBacktest'](arg1);
}

export function RunBackupNow(arg1) {
  return window['go']['main']['App']['RunBackupNow'](arg1);
}

export function RunCaoYuanStandardScanner4A(arg1) {
  return window['go']['main']['App']['RunCaoYuanStandardScanner4A'](arg1);
}

export function RunCaoYuanZhuangScanner4B(arg1) {
  return window['go']['main']['App']['RunCaoYuanZhuangScanner4B'](arg1);
}

export function RunCompositeScore(arg1) {
  return window['go']['main']['App']['RunCompositeScore'](arg1);
}

export function RunDipEntryScannerV8(arg1) {
  return window['go']['main']['App']['RunDipEntryScannerV8'](arg1);
}

export function RunFundamentalScan(arg1) {
  return window['go']['main']['App']['RunFundamentalScan'](arg1);
}

export function RunHotMoneyBreakoutScannerV7(arg1) {
  return window['go']['main']['App']['RunHotMoneyBreakoutScannerV7'](arg1);
}

export function RunLateDayChaseScanner(arg1) {
  return window['go']['main']['App']['RunLateDayChaseScanner'](arg1);
}

export function RunLimitPullbackScanner(arg1) {
  return window['go']['main']['App']['RunLimitPullbackScanner'](arg1);
}

export function RunLimitupRetraceScanner(arg1) {
  return window['go']['main']['App']['RunLimitupRetraceScanner'](arg1);
}

export function RunLowBuyBatchReplay(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunLowBuyBatchReplay'](arg1, arg2, arg3, arg4);
}

export function RunLowBuyReplayOnDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunLowBuyReplayOnDate'](arg1, arg2, arg3);
}

export function RunLowBuyScannerV1(arg1) {
  return window['go']['main']['App']['RunLowBuyScannerV1'](arg1);
}

export function RunMonsterScannerV10(arg1) {
  return window['go']['main']['App']['RunMonsterScannerV10'](arg1);
}

export function RunMonsterScannerV9(arg1) {
  return window['go']['main']['App']['RunMonsterScannerV9'](arg1);
}

export function RunOversoldIgniteScanner(arg1) {
  return window['go']['main']['App']['RunOversoldIgniteScanner'](arg1);
}

export function RunPaperStrategyAccount(arg1) {
  return window['go']['main']['App']['RunPaperStrategyAccount'](arg1);
}

export function RunPortfolioBacktest(arg1) {
  return window['go']['main']['App']['RunPortfolioBacktest'](arg1);
}

export function RunPositionMonitorOnce() {
  return window['go']['main']['App']['RunPositionMonitorOnce']();
}

export function RunQfqRebuild(arg1) {
  return window['go']['main']['App']['RunQfqRebuild'](arg1);
}

export function RunStrategyAccount(arg1, arg2) {
  return window['go']['main']['App']['RunStrategyAccount'](arg1, arg2);
}

export function RunStrategyAccountRisk(arg1, arg2) {
  return window['go']['main']['App']['RunStrategyAccountRisk'](arg1, arg2);
}

export function RunTailBuyScannerV6(arg1) {
  return window['go']['main']['App']['RunTailBuyScannerV6'](arg1);
}

export function RunTailForwardScan(arg1, arg2) {
  return window['go']['main']['App']['RunTailForwardScan'](arg1, arg2);
}

export function RunTailForwardScanAll(arg1) {
  return window['go']['main']['App']['RunTailForwardScanAll'](arg1);
}

export function RunTailLazyBatchReplay(arg1, arg2) {
  return window['go']['main']['App']['RunTailLazyBatchReplay'](arg1, arg2);
}

export function RunTailLazyReplayOnDate(arg1, arg2) {
  return window['go']['main']['App']['RunTailLazyReplayOnDate'](arg1, arg2);
}

export function RunTailLazyScannerV2(arg1) {
  return window['go']['main']['App']['RunTailLazyScannerV2'](arg1);
}

export function RunTripleVolumeScannerV5(arg1) {
  return window['go']['main']['App']['RunTripleVolumeScannerV5'](arg1);
}

export function RunWaveBacktest(arg1) {
  return window['go']['main']['App']['RunWaveBacktest'](arg1);
}

export function RunWaveScanner() {
  return window['go']['main']['App']['RunWaveScanner']();
}

export function RunWaveScannerWithGate(arg1) {
  return window['go']['main']['App']['RunWaveScannerWithGate'](arg1);
}

export function RunWaveTimingBacktest(arg1, arg2) {
  return window['go']['main']['App']['RunWaveTimingBacktest'](arg1, arg2);
}

export function RunXOpenBuy() {
  return window['go']['main']['App']['RunXOpenBuy']();
}

export function SaveTradeJournal(arg1) {
  return window['go']['main']['App']['SaveTradeJournal'](arg1);
}

export function SearchStocks(arg1) {
  return window['go']['main']['App']['SearchStocks'](arg1);
}

export function SellStockPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SellStockPosition'](arg1, arg2, arg3);
}

export function SendMeetingMessage(arg1) {
  return window['go']['main']['App']['SendMeetingMessage'](arg1);
}

export function SetActiveStrategy(arg1) {
  return window['go']['main']['App']['SetActiveStrategy'](arg1);
}

export function SetPaperAutoExit(arg1, arg2) {
  return window['go']['main']['App']['SetPaperAutoExit'](arg1, arg2);
}

export function SetPaperAutoPaused(arg1) {
  return window['go']['main']['App']['SetPaperAutoPaused'](arg1);
}

export function SetRegisterInviteCode(arg1) {
  return window['go']['main']['App']['SetRegisterInviteCode'](arg1);
}

export function SetRemoteUser(arg1, arg2) {
  return window['go']['main']['App']['SetRemoteUser'](arg1, arg2);
}

export function SetStockGroups(arg1, arg2) {
  return window['go']['main']['App']['SetStockGroups'](arg1, arg2);
}

export function SetTailForwardConfig(arg1, arg2) {
  return window['go']['main']['App']['SetTailForwardConfig'](arg1, arg2);
}

export function SetUserTrusted(arg1, arg2) {
  return window['go']['main']['App']['SetUserTrusted'](arg1, arg2);
}

export function SetXBloggerAutoBuy(arg1, arg2) {
  return window['go']['main']['App']['SetXBloggerAutoBuy'](arg1, arg2);
}

export function StartBoardReport(arg1) {
  return window['go']['main']['App']['StartBoardReport'](arg1);
}

export function StartDrillTapeBackfill(arg1, arg2) {
  return window['go']['main']['App']['StartDrillTapeBackfill'](arg1, arg2);
}

export function StartHistoryMinuteBackfill(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartHistoryMinuteBackfill'](arg1, arg2, arg3);
}

export function StartResearchReport(arg1, arg2) {
  return window['go']['main']['App']['StartResearchReport'](arg1, arg2);
}

export function SweepSecondWaveParams(arg1, arg2) {
  return window['go']['main']['App']['SweepSecondWaveParams'](arg1, arg2);
}

export function SyncTradeJournalWatchGroup() {
  return window['go']['main']['App']['SyncTradeJournalWatchGroup']();
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function TestMCPConnection(arg1) {
  return window['go']['main']['App']['TestMCPConnection'](arg1);
}

export function TestPush() {
  return window['go']['main']['App']['TestPush']();
}

export function UpdateAgentConfig(arg1) {
  return window['go']['main']['App']['UpdateAgentConfig'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateHistoryAutoCollect(arg1) {
  return window['go']['main']['App']['UpdateHistoryAutoCollect'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UpdatePaperPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePaperPosition'](arg1, arg2, arg3);
}

export function UpdateStockPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateStockPosition'](arg1, arg2, arg3, arg4);
}

export function UpdateStrategy(arg1) {
  return window['go']['main']['App']['UpdateStrategy'](arg1);
}

export function ValidateSecondWaveOOS(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateSecondWaveOOS'](arg1, arg2, arg3);
}

export function VerifyXBloggers(arg1, arg2) {
  return window['go']['main']['App']['VerifyXBloggers'](arg1, arg2);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsFullscreen() {
  return window['go']['main']['App']['WindowIsFullscreen']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
